src/AdminLTE/ViewComponents/MenuTaskViewComponent.cs
using AdminLTE.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AdminLTE.ViewComponents
{
    public class MenuTaskViewComponent : ViewComponent
    {

        public MenuTaskViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            var messages = GetData();
            return View(messages);
        }

        private List<Message> GetData()
        {
            var messages = new List<Message>();
            messages.Add(new Message
            {
                Id = 1,
                ShortDesc = "Design some buttons",
                URLPath = "#",
                Percentage = 20,
            });

            return messages;
        }
    }
}

src/AdminLTE/Views/Shared/Components/Header/Default.cshtml
<header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><img src="~/images/uob-logo_small.png" alt="adminlte" style="width:100%; padding:10px" /></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><img src="~/images/uob-logo.png" alt="adminlte" style="padding:5px; height: 50px" /></span>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        @*<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>*@
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu" style="border-radius:5px;background:#e8e9eb">
            <ul class="nav navbar-nav">
                    @*<!-- Messages: style can be found in dropdown.less-->
                @await Component.InvokeAsync("MenuMessage")
                <!-- /.messages-menu -->
                <!-- Notifications Menu -->
                @await Component.InvokeAsync("MenuNotification")
                <!-- Tasks Menu -->
                @await Component.InvokeAsync("MenuTask")*@
                    <!-- User Account Menu -->
                    @await Component.InvokeAsync("MenuUser")
                    <!-- Control Sidebar Toggle Button -->
                    @*<li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>*@
            </ul>
         </div>
</nav>
</header>